config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users do
    collection do
      get :index_json
    end
  end
  resources :salaries
  resources :performances
  resources :announcements
  resources :materials
  resources :articles
  resources :departments
  resources :companynews
  resources :vacation

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  include SessionsHelper
  before_action :logged_in

  def index
    params[:kind]="通知公告"
    @announcements=Article.search(params).paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    @announcement= Article.find_by_id(params[:id])
    @announcement[:title]=@announcement[:title].gsub('&nbsp;',' ')
    @announcement[:content]=@announcement[:content].gsub('<br/>',"\n").gsub('&nbsp;',' ')
  end

  def show
    @announcement= Article.find_by_id(params[:id])
  end

  def update
    @announcement= Article.find_by_id(params[:id])
    if @announcement.update_attributes(announcement_params)
      flash={:info => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to announcements_path, flash: flash
  end

  def destroy
    @announcement = Article.find_by_id(params[:id])
    @announcement.destroy
    redirect_to announcements_path(new: false), flash: {success: "公告已删除"}
  end

  def new
    @announcement=Article.new
  end

  def create
    @announcement=current_user.articles.new(announcement_params)
    if @announcement.save
      redirect_to announcement_path(@announcement), flash: {success: "添加成功"}
    else
      flash[:warning] = "添加公告失败,请重试"
      render 'new'
    end
  end

  private

  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def announcement_params
    params[:article][:kind]="通知公告"
    params[:article][:title]=params[:article][:title].gsub(/\s/,"&nbsp;")
    params[:article][:content]=params[:article][:content].gsub(/\r/,"<br/>").gsub(/\s/,"&nbsp;")
    params.require(:article).permit(:title,:content,:kind)
  end


end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_navside.html.erb
<div class="list-group list-group-root well">

  <a href="#" class="list-group-item" style="background-color:lavender"><strong><i class="fa fa-newspaper-o" aria-hidden="true"></i>
    信息发布</strong></a>
  <div class="list-group">
    <%= link_to announcements_path, class: "list-group-item" do %>
        <i class="fa fa-angle-right fa-fw"></i> 通知公告
    <% end %>
    <%= link_to departments_path, class: "list-group-item" do %>
        <i class="fa fa-angle-right fa-fw"></i> 部门概况
    <% end %>
    <%= link_to companynews_index_path, class: "list-group-item" do %>
        <i class="fa fa-angle-right fa-fw"></i> 公司新闻
    <% end %>
    <%= link_to materials_path, class: "list-group-item" do %>
        <i class="fa fa-angle-right fa-fw"></i> 资料下载
    <% end %>
  </div>

  <a href="#" class="list-group-item" style="background-color:lavender"><strong><i class="fa fa-microphone" aria-hidden="true"></i>
    会议安排</strong></a>
  <div class="list-group">
    <a href="#" class="list-group-item"><i class="fa fa-angle-right fa-fw"></i> 会议信息</a>
  </div>

  <a href="#" class="list-group-item" style="background-color:lavender"><strong><i class="fa fa-pencil-square-o" aria-hidden="true">
  </i> 规章制度</strong></a>
  <div class="list-group">
    <a href="#" class="list-group-item"><i class="fa fa-angle-right fa-fw"></i> 合同管理</a>
    <a href="#" class="list-group-item"><i class="fa fa-angle-right fa-fw"></i> 社会保险</a>
    <%= link_to vacations_path, class: "list-group-item" do %>
        <i class="fa fa-angle-right fa-fw"></i> 公时休假
    <% end %>
    <a href="#" class="list-group-item"><i class="fa fa-angle-right fa-fw"></i> 报销管理</a>
  </div>

</div>

app/views/announcements/edit.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'announcements/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> 编辑公告

      </div>
      <div class="panel-body" style="min-height: 450px">
        <%= form_for @announcement,url: announcement_path(@announcement), method: :patch,html: {role: 'form'} do |f| %>
            <%= render 'shared/error_messages', :object => @announcement %>
            <div class=" col-sm-12">
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">公告标题</div>
                  <%= f.text_field :title, class: 'form-control' %>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">公告正文</div>
                  <%= f.text_area :content, class: 'form-control' ,rows: 25%>
                </div>
              </div>
              <br>
              <div class="form-group">
                <%= f.submit '更新', class: "btn btn-info btn-block" %>
              </div>
              <div class="form-group">
                <%= link_to '取消', announcements_path, :class => "btn btn-default btn-block" %>
              </div>
              <br>
            </div>
        <% end %>

      </div>
    </div>


  </div>

</div>

app/views/announcements/index.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'announcements/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-newspaper-o fa-fw"></i> 通知公告
      </div>
      <div class="panel-body" style="min-height: 450px">
        <%= form_tag announcements_path, :method => 'get', role: 'form', class: "form-inline" do %>

            <div class="form-group">
              <%= text_field_tag :query, params[:query], placeholder: "搜索公告", class: 'form-control' %>
            </div>

            <%= button_tag(type: "submit", class: "btn btn-info", id: "filter-button") do %>
                <i class="fa fa-refresh"></i></span> 查找
            <% end %>

            <% if current_user.role==5 %>
              <%= link_to "新增公告", new_announcement_path, class: 'pull-right btn btn-success' %>
            <% end %>

        <% end %>


        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>公告标题</th>
            <th>作者</th>
            <th>发表时间</th>
            <% if current_user.role >3 %>
            <th>操作</th>
            <% end %>
          </tr>
          </thead>
          <tbody>
          <% @announcements.each do |announcement| %>
              <tr>
                <td><%= link_to raw("#{announcement.title}") ,announcement_path(id:announcement.id,page: params[:page])%></td>
                <td><%= announcement.user.name %></td>
                <td><%= announcement.created_at.to_formatted_s(:db) %></td>

                <% if current_user.role >3 %>
                    <td><%= link_to "编辑", edit_announcement_path(announcement), class: 'btn-sm btn-info' %></td>
                    <td><%= link_to "删除", announcement_path(announcement), method: :delete, class: 'btn-sm btn-danger' %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>

        <%= will_paginate @announcements, :param_name => 'page',
                          :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>

      </div>
    </div>


  </div>

</div>

app/views/announcements/new.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'announcements/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> 新增公告

      </div>
      <div class="panel-body" style="min-height: 450px">
        <%= form_for @announcement, url: announcements_path, html: {class: 'form-horizontal', role: 'form'} do |f| %>
            <%= render 'shared/error_messages', :object => @announcement %>
            <div class=" col-sm-12"><br/><br/>

              <div class="form-group">

                <div class="input-group">
                  <div class="input-group-addon">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题</div>
                  <%= f.text_field :title, class: 'form-control', placeholder: "输入公告标题" %>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">正&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;文</div>
                  <%= f.text_area :content, class: 'form-control',rows: 30, placeholder: "输入公告正文" %>
                </div>
              </div>




              <div class="form-group">
                <%= f.submit '添加', class: "btn btn-primary btn-block" %>
              </div>

              <div class="form-group">
                <%= link_to '取消', announcements_path, :class => "btn btn-default btn-block" %>
              </div>
            </div>

        <% end %>

      </div>
    </div>


  </div>

</div>

app/views/announcements/show.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'announcements/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-newspaper-o fa-fw"></i> 公告详情
        <div class="pull-right"><%= link_to "返回", announcements_path(page: params[:page]), class: 'btn-sm btn-primary' %></div>
      </div>
      <div class="panel-body" style="min-height: 450px">
        <h2 class="text-center"><%= raw @announcement.title %></h2>
        <p class="small text-muted text-center">
          <i class="fa fa-clock-o"><%= @announcement.created_at.to_formatted_s(:db) %></i><%= @announcement.user.name %>
        </p>

        <p>
          <%= raw @announcement.content %>
        </p>
      </div>
    </div>


  </div>

</div>