config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users do
    collection do
      get :index_json
    end
  end
  resources :salaries
  resources :performances
  resources :announcements
  resources :materials
  resources :articles
  resources :departments
  resources :companynews
  resources :vacation

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages
  has_many :articles
  has_many :materials
  belongs_to :department
  has_one :salary, :dependent => :destroy
  has_one :performance, :dependent => :destroy
  has_and_belongs_to_many :chats

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  before_save :downcase_email
  attr_accessor :remember_token
  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  #1. The ability to save a securely hashed password_digest attribute to the database
  #2. A pair of virtual attributes (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
  #3. An authenticate method that returns the user when the password is correct (and false otherwise)
  has_secure_password
  # has_secure_password automatically adds an authenticate method to the corresponding model objects.
  # This method determines if a given password is valid for a particular user by computing its digest and comparing the result to password_digest in the database.

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def self.filter_by_type(type)
    User.where("role = :type", type: type)
  end

  def self.none_hidden_users
    User.where("hidden = :type", type: false)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def user_remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def user_forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def user_authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


  def self.search(params)
    User.where("users.name LIKE ?", "%#{params[:query]}%")
  end

  def self.search_friends(params, current_user)
    User.all_except(current_user).all_except(current_user.friends).where("users.name LIKE ?", "%#{params[:query]}%")
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, except: [:index, :new, :index_json]
  before_action :logged_in, only: [:show]
  before_action :admin_logged_in, except: [:show, :index_json]
  before_action :correct_user, only: :show

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      @user.create_salary
      @user.create_performance
      redirect_to users_path, flash: {success: "添加成功"}
    else
      flash[:warning] = "账号信息填写有误,请重试"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash={:info => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to users_path, flash: flash
  end

  def destroy
    @user.destroy
    redirect_to users_path(new: false), flash: {success: "用户删除"}
  end

  def index
    @users=User.search(params).paginate(:page => params[:page], :per_page => 10)
  end

  def index_json
    @users=User.search_friends(params, current_user)
    render json: @users.as_json
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :sex, :department_id, :password,
                                 :phonenumber, :status)
  end

# Confirms a logged-in user.
  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def admin_logged_in
    if logged_in? and current_user.role==5
    else
      redirect_to root_url, flash: {:danger => '您没有这个权限'}
    end
  end

  def correct_user
    unless current_user == @user or current_user.role == 5
      redirect_to user_path(current_user), flash: {:danger => '您没有权限浏览他人信息'}
    end
  end

  def set_user
    @user=User.find_by_id(params[:id])
    if @user.nil?
      redirect_to root_path, flash: {:danger => '没有找到此用户'}
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def available_user
    return  @users- [User.find_by_name("无作者")]
  end
end

app/views/users/_navside.html.erb
<div class="list-group">
  <%= link_to users_path, class: 'list-group-item' do %>
      <i class="fa fa-user fa-fw"></i> 员工信息 <span class="badge"><%= User.all.length%></span>
  <% end %>
  <%= link_to salaries_path, class: 'list-group-item' do %>
      <i class="fa fa-book fa-fw"></i> 薪酬管理
  <% end %>
  <%= link_to performances_path, class: 'list-group-item' do %>
      <i class="fa fa-money fa-fw"></i> 绩效考核
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'users/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> 编辑用户

      </div>
      <div class="panel-body" style="min-height: 450px">

        <%= form_for @user, html: {role: 'form'} do |f| %>
            <%= render 'shared/error_messages', :object => @user %>
            <div class=" col-sm-12"><br/><br/>
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</div>
                  <%= f.text_field :name, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别</div>
                  <%= f.text_field :sex, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">

                <div class="input-group">
                  <div class="input-group-addon">邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</div>
                  <%= f.text_field :email, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</div>
                  <%= f.text_field :password_digest, class: 'form-control' %>
                </div>
              </div>



              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">所属部门</div>
                  <%= f.select :department_id, options_for_select(Department.all.map{|depart| [depart.name,depart.id]}, [@user.department.name,@user.department.id]),class: 'form-control'%>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">联系方式</div>
                  <%= f.text_field :phonenumber, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">状&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;态</div>
                  <%= f.text_field :status, class: 'form-control' %>
                </div>
              </div>


              <br>
              <div class="form-group">
              <%= f.submit '更新', class: "btn btn-info btn-block" %>
              </div>
              <div class="form-group">
              <%= link_to '取消', users_path, :class => "btn btn-default btn-block" %>
              </div>
              <br>
            </div>
        <% end %>
      </div>
    </div>


  </div>

</div>

app/views/users/index.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'users/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> 用户管理
        <%= form_tag users_path, :method => 'get', role: 'form', class: "form-inline" do %>
            <br/>
            <div class="form-group">
              <%= text_field_tag :query, params[:query], placeholder: "搜索用户", class: 'form-control' %>
            </div>

            <%= button_tag(type: "submit", class: "btn btn-info", id: "filter-button") do %>
                <i class="fa fa-refresh"></i></span> 查找
            <% end %>
            <div class="pull-right" style="margin-right:17%"><%= link_to "新增", new_user_path, class: 'btn-sm btn-primary' %></div>
        <% end %>
      </div>
      <div class="panel-body" style="min-height: 450px">

        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>员工ID</th>
            <th>姓名</th>
            <th>性别</th>
            <th>部门</th>
            <th>联系方式</th>
            <th>状态</th>
            <th>操作</th>

          </tr>
          </thead>
          <tbody>
          <% available_user.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to "#{user.name}",user_path(id:user.id,page: params[:page]) %></td>
                <td><%= user.sex %></td>
                <td><%= user.department.name %>
                <td><%= user.phonenumber %></td>
                <td><%= user.status %></td>

                <% if current_user.role >3 %>
                    <td><%= link_to "编辑", edit_user_path(user), class: 'btn-sm btn-info' %></td>
                    <td><%= link_to "删除", user_path(user), method: :delete, class: 'btn-sm btn-danger' %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>

        <%= will_paginate @users, :param_name => 'page',
                          :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>

      </div>
    </div>


  </div>

</div>

app/views/users/new.html.erb
<div class="row">

  <div class="col-sm-2">
    <%= render 'users/navside' %>
  </div>

  <div class="col-sm-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> 新增用户

      </div>
      <div class="panel-body" style="min-height: 450px">
        <%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
            <%= render 'shared/error_messages', :object => @user %>
            <div class=" col-sm-12"><br/><br/>

              <div class="form-group">

                  <div class="input-group">
                    <div class="input-group-addon">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</div>
                    <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
                  </div>
              </div>

              <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</div>
                    <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
                  </div>
              </div>


              <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</div>
                    <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
                  </div>
              </div>

              <div class="form-group">

                  <div class="input-group">
                    <div class="input-group-addon">确认密码</div>
                    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
                  </div>

              </div>
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon">所属部门</div>
                  <%= f.select :department_id, options_for_select(Department.all.map{|depart| [depart.name,depart.id]}),class: 'form-control' %>
                </div>
              </div>
              <br/>

              <div class="form-group">
                  <%= f.submit '注册', class: "btn btn-primary btn-block" %>
              </div>

              <div class="form-group">
                <%= link_to '取消', users_path, :class => "btn btn-default btn-block" %>
              </div>
            </div>

        <% end %>

      </div>
    </div>


  </div>

</div>

app/views/users/show.html.erb
<% performance=@user.performance
   salary=@user.salary
%>

<div class="row">
  <% if current_user.role==5 %>
      <div class="col-sm-2">
        <%= render 'users/navside' %>
      </div>
  <% end %>

  <div class="col-sm-1<%= current_user.role==5 ? "0" : "2" %>">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-users fa-fw"></i> <%= @user.name %> 的个人信息
        <% if current_user.role==5 %>
            <div class="pull-right"><%= link_to "返回", users_path(page: params[:page]), class: 'btn-sm btn-primary' %></div>
        <% end %>
      </div>
    </div>


    <div class="row">

      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <i class="fa fa-users fa-fw"></i> 基本信息
          </div>
          <div class="panel-body" id="profile-1">
            <br/>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">职工编号</div>
                <div class="form-control"><%= @user.id %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</div>
                <div class="form-control"><%= @user.name %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别</div>
                <div class="form-control"><%= @user.sex %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话</div>
                <div class="form-control"><%= @user.phonenumber %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</div>
                <div class="form-control"><%= @user.email %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">部&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;门</div>
                <div class="form-control"><%= @user.department.name  %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">状&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;态</div>
                <div class="form-control"><%= @user.status %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">权&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;限</div>
                <div class="form-control"><%= @user.role %></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <i class="fa fa-users fa-fw"></i> 薪酬情况
          </div>
          <div class="panel-body" id="profile-2">
            <br/>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">基本工资</div>
                <div class="form-control"><%= salary.basic %>元</div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">基本奖金</div>
                <div class="form-control"><%= salary.bonus %>元</div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">医疗保险</div>
                <div class="form-control"><%= salary.insurence %>元</div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">考核扣发</div>
                <div class="form-control"><%= salary.pulishment %>元</div>
              </div>
              <br/>
            </div>

          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <i class="fa fa-users fa-fw"></i> 考核状况
          </div>
          <div class="panel-body" id="profile-3">

            <br/>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">迟到次数</div>
                <div class="form-control"><%= performance.arriving_late %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">请假次数</div>
                <div class="form-control"><%= performance.leaving %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">培训成绩</div>
                <div class="form-control"><%= performance.training_score %></div>
              </div>
              <br/>
              <div class="input-group">
                <div class="input-group-addon">综合评价</div>
                <div class="form-control"><%= performance.evaluation %></div>
              </div>
              <br/>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
    $(function () {
        var obj1 = $("#profile-1");
        var obj2 = $("#profile-2");
        var obj3 = $("#profile-3");
        var h1 = obj1.height();
        var h2 = obj2.height();
        var h3 = obj3.height();
        if (h1 < h2) h1 = h2;
        if (h1 < h3) h1 = h3;
        obj1.height(h1);
        obj2.height(h1);
        obj3.height(h1);
    });
</script>