config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users do
    collection do
      get :index_json
    end
  end
  resources :salaries
  resources :performances
  resources :announcements
  resources :materials
  resources :articles
  resources :departments
  resources :companynews
  resources :vacation

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :messages, :dependent => :destroy
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include SessionsHelper
  include ChatsHelper
  respond_to :js, :html
  before_action :logged_in
  before_action :set_chat, except: [:index, :new, :create]
  before_action :correct_user, only: :show

  def index
    @all_users=User.all
  end

  def add_user
    params[:users].each do |id|
      @chat.users<<User.find_by_id(id)
    end
    redirect_to chat_path(@chat), flash: {:info => "用户已成功拉入群聊"}
  end

  def delete_user
    user=User.find_by_id(params[:user_id])
    @chat.users.delete(user)
    redirect_to chat_path(@chat), flash: {:warning => "#{user.name}已成功退出群聊"}
  end

  def create
    user=User.find_by_id(params[:users])

    current_user.chats.each do |chat|
      if (chat.users-[user, current_user]).blank?
        redirect_to chat_path(chat) and return
      end
    end

    @chat = Chat.new
    @chat.users<<user
    @chat.users<<current_user
    @chat.admin_id=current_user.id
    @chat.name="#{user.name}-#{current_user.name}"

    if @chat.save
      redirect_to chat_path(@chat)
    else
      flash[:warning] = "错误,请重试"
      render chats_path, flash: flash
    end
  end

  def update
    if @chat.update_attributes(chat_params)
      flash= {success: "修改成功"}
    else
      flash= {danger: "修改失败，请重试"}
    end
    redirect_to chat_path(@chat), flash: flash
  end

  def trans_auth
    @chat.update_attribute(:admin_id, params[:admin_id])
    redirect_to chat_path(@chat), flash: {success: '移交成功！'}
  end

  def destroy
    @chat.destroy
    redirect_to chats_path, flash: {:danger => '聊天已删除'}
  end

  def show
    @new_message = Message.new
    @all_users=User.all
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :description)
  end

  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def set_chat
    @chat=Chat.find_by_id(params[:id])
    if @chat.nil?
      redirect_to chats_path, flash: {:warning => "没有找到此次聊天的信息"}
    end
  end

  def correct_user
    if @chat.users.include?(current_user)
    else
      redirect_to chats_path, flash: {warning: '您没有权限无法进入此聊天室'}
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper

  def contact_active
    'active' if params[:action]=='index'
  end

  def chat_active
    'active' if params[:action]=='show'
  end

end

app/views/chats/_chat_info.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-comments fa-fw"></i> 房间信息
  </div>
  <div class="panel-body">

    <table class="table">
      <tbody>
      <tr>
        <td width="40%">房间名:</td>
        <td><%= @chat.name %></td>
      </tr>
      <tr>
        <td>当前用户:</td>
        <td>
          <% @chat.users.each do |user| %>
                  <span class="label label-warning"><%= user.name %>
                    <% if current_user.id==@chat.admin_id %>
                        <%= link_to delete_user_chat_path(user_id: user.id, id: @chat.id), method: :delete, style: 'color:red;' do %>
                            <i class="fa fa-times"></i>
                        <% end %>
                    <% end %>
                  </span>
          <% end %>
        </td>
      </tr>
      </tbody>
    </table>
    <hr>
    <% if current_user.id==@chat.admin_id %>

        <button data-toggle="collapse" data-target="#add-user" class="btn btn-info btn-block" style="margin-bottom: 5px;">添加用户</button>
        <div id="add-user" class="collapse">
          <div class="well">
            <%= form_for @chat, url: add_user_chat_path(@chat), method: :post, role: 'form' do |f| %>
                <label for="users">选择加入聊天的用户：</label>
                <%= select_tag :users, options_for_select((@all_users-@chat.users).map { |user| [user.name, user.id] }), class: "js-example-basic-multiple", multiple: "multiple", multiple: true, style: "width: 100%" %>
                <%= f.submit '确定', class: 'btn btn-success btn-block', style: 'margin-top:10px;margin-bottom:10px ' %>
            <% end %>
            <button data-toggle="collapse" data-target="#add-user" class="btn btn-default btn-block"> 取消</button>
          </div>
        </div>

        <button data-toggle="collapse" data-target="#edit-room" class="btn btn-primary btn-block" style="margin-bottom: 5px;">修改房间名</button>
        <div id="edit-room" class="collapse">
          <div class="well">
            <%= form_for @chat, url: chat_path(@chat), method: :patch, role: "form" do |f| %>
                <div class="form-group">
                  <label for="name">编辑房间名:</label>
                  <%= f.text_field :name, class: "form-control" %>
                </div>
                <%= f.submit '确定', class: 'btn btn-success btn-block', style: 'margin-top:10px;margin-bottom:10px ' %>
            <% end %>
            <button data-toggle="collapse" data-target="#edit-room" class="btn btn-default btn-block"> 取消</button>
          </div>
        </div>

        <button data-toggle="collapse" data-target="#trans-auth" class="btn btn-danger btn-block">转移权限</button>
        <div id="trans-auth" class="collapse">
          <div class="well">
            <%= form_for @chat, url: trans_auth_chat_path(@chat), method: :patch, role: 'form' do |f| %>
                <label for="users">移交此房间管理权限给：</label>
                <%= select_tag :admin_id, options_for_select((@chat.users-[current_user]).map { |user| [user.name, user.id] }), class: "js-example-basic-multiple", style: "width: 100%" %>
                <%= f.submit '确定', class: 'btn btn-success btn-block', style: 'margin-top:10px;margin-bottom:10px ' %>
            <% end %>
            <button data-toggle="collapse" data-target="#trans-auth" class="btn btn-default btn-block"> 取消</button>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">

    $(".js-example-basic-multiple").select2();
    $(".js-example-basic-single").select2();

</script>

app/views/chats/_navside.html.erb
<div class="panel with-nav-tabs panel-info">
  <div class="panel-heading">
    <ul class="nav nav-tabs">
      <li class=<%= contact_active %>><a href="#contact-tab" data-toggle="tab"><i class="fa fa-book"></i>通讯录</a></li>
      <li class=<%= chat_active %>><a href="#chat-tab" data-toggle="tab"><i class="fa fa-weixin"></i>聊天</a></li>
    </ul>
  </div>
  <div class="panel-body" id="tab-panel-body">
    <div class="tab-content">
      <div class="tab-pane fade in <%= contact_active %>" id="contact-tab">
        <ul class="list-group">
          <% current_user.friends.each do |user| %>
              <li class="list-group-item" style="padding: 0px; margin-bottom: 0px;">

                <button class="btn btn-default btn-block" data-toggle="collapse" data-target="#user-<%= user.id %>" id="tab-contact-default">
                  <%= image_tag "user-icon.png", class: "img-sm" %>
                  <div class="text-muted">
                    <%= user.name %>
                  </div>
                </button>

                <div id="user-<%= user.id %>" class="collapse">
                  <%= form_for Chat.new, url: chats_path, method: :post do |f| %>
                      <%= hidden_field_tag :users, [user.id] %>
                      <%= button_tag(:class => "btn btn-success btn-block", style: "border-radius: 0;") do %>
                          <i class="fa fa-angle-right"></i> 发起聊天
                      <% end %>
                  <% end %>
                  <%= link_to user_path(user), class: 'btn btn-info btn-block', role: "button", style: "border-radius: 0" do %>
                      <i class="fa fa-angle-right"></i> 用户详情
                  <% end %>
                  <%= link_to friendship_path(user), method: :delete, class: 'btn btn-danger btn-block', role: "button", style: "border-radius: 0;margin:0px;" do %>
                      <i class="fa fa-angle-right"></i> 删除用户
                  <% end %>
                </div>
              </li>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane fade in <%= chat_active %>" id="chat-tab">
        <ul class="list-group">
          <% current_user.chats.each do |chatroom| %>
              <%= link_to chat_path(chatroom), class: 'list-group-item' do %>
                  <i class="fa fa-wechat fa-5"></i> <%= truncate(chatroom.name, length: 10) %>
                  <text id="chatroom-<%= chatroom.id %>"></text>
              <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="panel-footer">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#myModal">添加朋友
    </button>
  </div>
</div>

<%= render "search_fridends" %>

app/views/chats/_search_fridends.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">查找用户</h4>
      </div>
      <div class="modal-body">

        <form class="form-incline" id="search-friend">

          <div class="input-group">
            <%= text_field_tag :query, params[:query], placeholder: "搜索用户", class: 'form-control' %>
            <span class="input-group-btn">
                    <button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </span>
          </div>
        </form>
        <hr>

        <table class="table table-striped table-hover" id="result">
          <thead>
          </thead>
          <tbody>
          </tbody>
        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>

</div>
<script>
    $('#search-friend').submit(function () {
        var valuesToSubmit = $(this).serialize();
        $.ajax({
            type: 'GET',
            url: '/users/index_json',
            dataType: "JSON",
            data: valuesToSubmit,
            success: function (data) {
                $('#result tr').remove();
                $('#result text').remove();

                if (data != "") {
                    $('#result thead').html("<tr><th>姓名</th><th>性别</th><th>联系方式</th><th></th></tr>");
                    $.each(data, function (index, user) {
                        $('#result tbody').append("<tr><td>" + user.name + "</td><td>" + user.sex + "</td><td>" + user.email + "</td><td><a class='btn btn-success btn-xs' data-method='post' href='/friendships?friend_id=" + user.id + "'>添加</a></td></tr>");
                    });
                } else {
                    $('#result tbody').append("<text>没有找到符合条件的用户</text>")
                }

            }, error: function () {
                alert('error in post');
            }
        });
        return false;
    });

</script>

app/views/chats/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= render 'chats/navside' %>
  </div>
  <div class="col-sm-10">
  </div>
</div>

app/views/chats/show.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= render 'chats/navside' %>
  </div>

  <div class="col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-comments fa-fw"></i> Chat
        <div class="btn-group pull-right">
          <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-chevron-down"></i>
          </button>
          <ul class="dropdown-menu slidedown">

            <% if current_user.id==@chat.admin_id %>
                <li>
                  <%= link_to destroyall_messages_path(chat_room: @chat.id), method: :delete do %>
                      <i class="fa fa-info-circle fa-fw"></i> 清空历史记录
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to chat_path(@chat), method: :delete do %>
                      <i class="fa fa-times fa-fw"></i> 删除聊天
                  <% end %>
                </li>
            <% else %>
                <li>
                  <%= link_to delete_user_chat_path(user_id: current_user.id, id: @chat.id), method: :delete do %>
                      <i class="fa fa-times"></i> 退出聊天
                  <% end %>
                </li>
            <% end %>

          </ul>
        </div>
      </div>

      <div class="panel-body">
        <!--Widget body-->
        <div id="demo-chat-body" class="collapse in">
          <div class="nano has-scrollbar" style="height:375px">
            <div class="nano-content pad-all" tabindex="0" style="right: -17px;">
              <ul class="list-unstyled media-block">

                <%= sync partial: 'message_row', collection: Message.by_chat(@chat), refetch: true %>
                <%= sync_new partial: 'message_row', resource: Message.new, scope: @chat, refetch: true %>

              </ul>
            </div>
            <div class="nano-pane">
              <div class="nano-slider" style="height: 141px; transform: translate(0px, 0px);"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="panel-footer">
        <%= form_for @new_message, remote: true do |f| %>
            <div class="input-group">
              <%= f.text_field :body, class: "form-control input-sm", placeholder: "Type your message here..." %>
              <span class="input-group-btn"> <%= f.submit "发送", class: "btn btn-warning btn-sm" %> </span>
              <%= hidden_field_tag :chat_room, @chat.id %>
            </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-3">
    <%= render 'chat_info' %>
  </div>
</div>


<script type="text/javascript">
    var $cont = $('.nano-content');
    $cont[0].scrollTop = $cont[0].scrollHeight;
</script>