config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users do
    collection do
      get :index_json
    end
  end
  resources :salaries
  resources :performances
  resources :announcements
  resources :materials
  resources :articles
  resources :departments
  resources :companynews
  resources :vacation

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :department

  def self.search(params)
    articles=Article.where("articles.title LIKE :title and articles.kind= :kind ",title: "%#{params[:query]}%",kind: params[:kind])
    return articles
  end
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :messages, :dependent => :destroy
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_one :article,:dependent => :destroy
  has_many :users


  def self.search(params)
    departments=Department.where("departments.name LIKE ?", "%#{params[:query]}%")
    return departments
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/material.rb
class Material < ActiveRecord::Base
  attr_accessor :file
  has_attached_file :file
  belongs_to :user
  validates_attachment_content_type :file, :content_type => ["application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/octet-stream"]

  def self.search(params)
    materials=Material.where("materials.file_file_name LIKE ?", "%#{params[:query]}%")
     return materials
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat

  sync :all
  sync_scope :by_chat, ->(chat) { where(chat_id: chat.id) }
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :user
end

app/models/salary.rb
class Salary < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages
  has_many :articles
  has_many :materials
  belongs_to :department
  has_one :salary, :dependent => :destroy
  has_one :performance, :dependent => :destroy
  has_and_belongs_to_many :chats

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  before_save :downcase_email
  attr_accessor :remember_token
  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  #1. The ability to save a securely hashed password_digest attribute to the database
  #2. A pair of virtual attributes (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
  #3. An authenticate method that returns the user when the password is correct (and false otherwise)
  has_secure_password
  # has_secure_password automatically adds an authenticate method to the corresponding model objects.
  # This method determines if a given password is valid for a particular user by computing its digest and comparing the result to password_digest in the database.

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def self.filter_by_type(type)
    User.where("role = :type", type: type)
  end

  def self.none_hidden_users
    User.where("hidden = :type", type: false)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def user_remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def user_forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def user_authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


  def self.search(params)
    User.where("users.name LIKE ?", "%#{params[:query]}%")
  end

  def self.search_friends(params, current_user)
    User.all_except(current_user).all_except(current_user.friends).where("users.name LIKE ?", "%#{params[:query]}%")
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper

  def contact_active
    'active' if params[:action]=='index'
  end

  def chat_active
    'active' if params[:action]=='show'
  end

end

app/helpers/companynews_helper.rb
module CompanynewsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  # 点击log_out,安全退出.只关闭浏览器时会保存cookie,安全退出后就没有了
  def log_out
    forget_user(current_user)
    session.delete(:user_id)
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if session[:user_id]
      @current_user||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.user_authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember_user(user)
    user.user_remember
    # Because it places the id as plain text, this method exposes the form of the application’s cookies
    # and makes it easier for an attacker to compromise user accounts. To avoid this problem,
    # we’ll use a signed cookie, which securely encrypts the cookie before placing it on the browser:
    cookies.signed[:user_id] = {value: user.id, expires: 5.minutes.from_now.utc}
    cookies[:remember_token] = {value: user.remember_token, expires: 5.minutes.from_now.utc}
  end

  def forget_user(user)
    user.user_forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    user == current_user
  end


end

app/helpers/users_helper.rb
module UsersHelper
  def available_user
    return  @users- [User.find_by_name("无作者")]
  end
end

app/helpers/vacation_helper.rb
module VacationHelper
end

app/views/layouts/_content.html.erb
<script type="text/javascript">
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    <% flash.each do |message_type,message| %>
    <% message_type = 'error'   if message_type == 'danger'%>
    toastr['<%= message_type %>']('<%= message %>');
    <% end %>
</script>

<br>
<div class="container-fluid">
  <%= yield %>
</div>


<%# flash.each do |message_type, message| %>
<!--<div class="alert alert-<%#= message_type %>">-->
<!--<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
<!--<strong> <%#= message %></strong>-->
<!--</div>-->
<%# end %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <footer class="container-fluid">
    <p class="text-center">中国科学院大学版权所有 © 2016
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand', style: "color:white" do %>
          <i class="fa fa-leaf" aria-hidden="true"></i> YAOYU管理系统
      <% end %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <% if current_user %>

            <li class="dropdown">
              <a class="dropbtn">办公事务</a>
              <div class="dropdown-content">
                <%= link_to announcements_path do %><i class="fa fa-angle-right fa-fw"></i> 通知公告
                <% end %>
                <%= link_to announcements_path do %><i class="fa fa-angle-right fa-fw"></i> 会议安排
                <% end %>
                <%= link_to announcements_path do %><i class="fa fa-angle-right fa-fw"></i> 规章制度
                <% end %>
              </div>
            </li>
            <% if current_user.role==5 %>

              <li> <%= link_to "原材料管理", users_path %></li>

              <li class="dropdown">
                <a class="dropbtn">人事管理</a>
                <div class="dropdown-content">
                  <%= link_to users_path do %><i class="fa fa-angle-right fa-fw"></i> 员工信息
                  <% end %>
                  <%= link_to users_path do %><i class="fa fa-angle-right fa-fw"></i> 绩效考核
                  <% end %>
                  <%= link_to salaries_path do %><i class="fa fa-angle-right fa-fw"></i> 薪酬管理
                  <% end %>
                </div>
              </li>

              <li> <%= link_to "工程预决算", users_path %></li>
              <li> <%= link_to "厂内生产管理", users_path %></li>
              <li> <%= link_to "工地管理", users_path %></li>
              <li> <%= link_to "后勤管理", users_path %></li>
            <% end %>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>

            <li>
              <%= link_to user_path(current_user), class: "dropbtn" do %>
                  <%=current_user.name%> <span class="glyphicon glyphicon-user"></span>
              <% end %>
            </li>

            <li>
              <%= link_to chats_path, class: "dropbtn" do %>
                  私信 <i class="fa fa-wechat"></i>
              <% end %>
            </li>

            <li>
              <p class="navbar-text"><%= current_user.department.name %></p>
            </li>

            <li>
              <%= link_to sessions_logout_path, method: :delete, class: "dropbtn" do %>
                  退出 <span class="	glyphicon glyphicon-off"></span>
              <% end %>
            </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= render 'layouts/login_panel' %>

app/views/layouts/_login_panel.html.erb
<!-- Modal -->
<div class="modal fade" id="panel_modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4><span class="glyphicon glyphicon-lock"></span> 登录</h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">

        <%= form_for(:session, url: sessions_login_path, method: :post, html: {role: 'form'}) do |f| %>

            <div class="form-group">
              <%= f.label :email, "账号密码登陆" %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>

            <div class="checkbox">
              <label><%= f.check_box :remember_me %>记住我</label>
            </div>

            <%= button_tag(type: "submit", class: "btn btn-primary btn-block") do %>
                <span class="glyphicon glyphicon-off"></span> 登陆
            <% end %>

        <% end %>
      </div>

      <div class="modal-footer">
        <p class="text-center">没有账号? 请联系管理员</p>
      </div>

    </div>

  </div>

</div>

<script>
  $(document).ready(function () {
    $("#login_panel").click(function (e) {
      e.preventDefault();
      $("#panel_modal").modal();
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YAOYU!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= include_sync_config %>
  <meta>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>

<body>

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%#= render partial: 'layouts/footer' %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>